services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: pos-postgres-dev
    environment:
      POSTGRES_DB: pos_system
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - pos-network

  # Golang Backend API (Development)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
      target: development
    container_name: pos-backend-dev
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres123
      - DB_NAME=pos_system
      - PORT=8080
      - GIN_MODE=debug
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - pos-network
    volumes:
      - ./backend:/app
    restart: unless-stopped

  # Frontend (Development)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
      target: development
    container_name: pos-frontend-dev
    environment:
      - VITE_API_URL=http://localhost:8080
    ports:
      - "3000:3000"
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - pos-network
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped

volumes:
  postgres_dev_data:

networks:
  pos-network:
    driver: bridge

